### ISSUE TITLE
Is UUID for keyfile/header supported?

### ISSUE THREAD

**Issue by xenithorb** [johnlane/grub#14]
i.e. "How do I use a USB drive with a keyfile or header on it and ensure the path is consistent"

**Comment by johnlane** [comment]
I presume you refer to the `cryptomount -k (hd0,1)/keyfile ...`?

The provided extensions do not alter the ways that a device can be addressed. If Grub supports it then I think it should work. But that's a glib statement and it isn't that simple :)

The problem is that "raw" devices containing headers  or keyfiles don't have a UUID by which they can be identified.  Grub knows how to identify a LUKS device from the UUID in its attached header but it cannot identify a LUKS (or dm-crypt) device that has no header. It does not know anything about header files or key files so wouldn't be able to identify a device based on a header _file_ on it containing a certain UUID. It _might_ identify a USB stick that _only_ contained a header written directly to the device (rather than in a file) but I don't know. I haven't tried anything like this.

The issue of reliably identifying "headerless" devices has been [discussed on the ML](http://lists.gnu.org/archive/html/help-grub/2017-02/msg00029.html) and I did suggest that perhaps  Grub might be able to support the physical device identifier (like `ata-ST31500341AS_7VS1GB18`) but this remains a problem without a solution.

----
FWIW my use case has been booting from the USB stick containing the detached headers and keys. The device containing them is encrypted and, by the time they're used, are guaranteed to be under `(crypto0)` so identification isn't a problem that I have.

**Comment by xenithorb** [comment]
Yeah the question is a follow-up to this: https://github.com/johnlane/grub/issues/13 and I thought it should be asked separately. 

>FWIW my use case has been booting from the USB stick containing the detached headers and keys. The device containing them is encrypted and, by the time they're used, are guaranteed to be under (crypto0) so identification isn't a problem that I have.

Well that's close to what I had in mind... So that answers my question, I need to encrypt the external device and that's the only way for it to have a consistent identifier, is that correct?

That's really the major problem here, is that I just didn't understand how to address the keyfile in such a way that would always work, no matter where the USB was plugged in.

**Comment by johnlane** [comment]
I should write up my usage pattern and put it on the website. Plus a note clarifying the situation regarding automated config.

But, to summarise it... the machines I boot have no bootloader on their internal storage. The internal storage is encrypted, depeding on my needs as LUKS on LVM or LVM on LUKS. I have a USB stick that contains the pacthed Grub bootloader. It boots a normal unencrypted `grub.cfg` that presents a menu. The menu offers options to boot a number of live ISOs (also on the stick) plus an item which leads to a second `grub.cfg` in an encrypted partition. Selecting that option prompts for the passphrase to unlock the encrypted partition. The encrypted partition contains the header and key files required by the second `grub.cfg`. Those headers and keys unlock the machine's internal storage so that Grub can read the kernel and initramfs. The initramfs (located on the encrypted internal storage) also contains the same header and key files so that the booting kernel may also unlock its root filesystem. Oh, and one USB stick can boot several such configured machines - the second `grub.cfg` offers a menu of machines it can boot (options select the relevant headers and keys).

All of that works and I have been using that setup since I first patched Grub. Being able to do this was the impetus for patching Grub in the first place. Hopefully that explanation helps but I'll post an update here when I update the website.

**Comment by johnlane** [comment]
I've updated the website with a [supplementary page](http://grub.johnlane.ie/grubby-usb.html) using notes I made some time ago. They basically cover how I created an encrypted bootable USB stick, plus various bits of other background information. I hope it's of use to you.

**Comment by Yannik** [comment]
@johnlane As a follow-up to your explanations: In the grub.cfg on your encrypted usb stick partition, you hardcoded the encrypted partition of the machine you want to boot as (hdX,gptY)?

**Comment by johnlane** [comment]
@Yannick do you refer to this:
```
crypt_start af4b9159-8cbb-4122-b801-0c18adf26b3e hd1,1 /dev/sda1 ...
```
where I have explicitly stated `hd1,1` and `/dev/sda1` ?

Yes the device is hard coded. It is a limitation of the encrypted partitions that they cannot be autodetected.

**Comment by Yannik** [comment]
@johnlane Yeah, I read the suggestion of using device model/serial number on the ml. Just wanted to clarify.

**Comment by johnlane** [comment]
I think the device model/serial number would work nicely but I didn't have the time to delve into the code to work out how to do it. If this work does ever get taken upstream it might spur me on to look at autodetection based on device model/serial number.

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
