### ISSUE TITLE
Offer patches to grub mailing list again?

### ISSUE THREAD

**Issue by Yannik** [johnlane/grub#15]
From my reading of the grub mailing list, the latest information is, that they would consider to include your patches in the next release (source: https://lists.gnu.org/archive/html/help-grub/2017-02/msg00030.html)

Perhaps you could try to get some updates on this? I thank you alot for these patches and would love to see them included in grub.

**Comment by johnlane** [comment]
@Yannik yes that is what was said. I think it would be better if others pushed for this rather than just me so it can be seen that others want it. Perhaps you might like to raise it with them. If they want the patches then I will update everything and pass them on (but nothing has changed since the last time that I updated it).

I'm going to close this issue becuase there is [another one](https://github.com/johnlane/grub/issues/1) already tracking the issue of upstream inclusion.

**Comment by Yannik** [comment]
@johnlane I've written an email to grub-devel. I will revisit the issue on grub-help if I get no reply (feel free to remind me in case I forget)

**Comment by Yannik** [comment]
@johnlane I received the following reply:

> 
> May I ask you or the original author to rebase the patches
> on the latest master? Then I will take a look. And please
> do not forget to CC me.
> 
> Daniel
> 

could you possibly take care of this, as you know the code best?

**Comment by johnlane** [comment]
@yannick I will rebase the patches. I do it periodically anyway so now is as good a time as any. I'll report back here once I have reposted them and I will reply to Daniel on the mailing list.

**Comment by Yannik** [comment]
@johnlane Great!

**Comment by johnlane** [comment]
@Yannik Patches applied and sent to ML. I also updated the grup-crypt site.
