### ISSUE TITLE
Installation problem with grub

### ISSUE THREAD

**Issue by Tuxuser-Tijon** [johnlane/grub#16]
Hello John,
I tried to install your enhanced grub for detached LUKS header support. This is my layout and what I did:
Harddisk SDD LUKS container, detached header, with three LVM partitions (root, home, swap).
USB disk with three partitions (unencrypted EFI partition, encrypted partition, data partition), with only the unencrypted EFI partition as part of my system (according to your guide option where header and key stay on the unencrypted partition).
I used ubuntu-18.04-desktop-amd64.iso on another USB stick to start my system, then
$ git clone https://git.savannah.gnu.org/git/grub.git
,applied all 7 patches that you provide on grub.johnlane.ie, and compiled grub.
Then I opened the encrypted harddisk, mounted everything in /mnt (the USB EFI partition in /boot/efi) and chrooted into mnt.
When I want to install your enhanced grub via
$ grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub  --debug --removable
the installation throws this error:
'grub-install: error: disk 'lvmid/cV0tl0-NAPw-IFfb-LPIj-lPNX-O3Wu-FhQOT2/J1EzYu-twuQ-gpbz0-Ai3y-5Dkd-t55s-T41t1h' not found.'
I turn to your github issue page because I was not able to figure out how to avoid that error on the net. In case you have a suggestion where to look, I would be very thankful.
Best regards,
Paul

**Comment by johnlane** [comment]
Hello Paul,

I have not tried this on an EFI system because I don't have one, so that command-line isn't familiar to me. When I use `grub-install` with a BIOS, it goes like this:
```
# grub-install --no-floppy --boot-directory=/mnt /dev/sdj
```
where `/mnt` is where the grub files get written to (e.g. what would normally be `/boot` but in my case is the plaintext filesystem on my usb stick and `sdj` is the usb stick. I describe this on the [example](http://grub.johnlane.ie/grubby-usb.html) linked from the [main page of my web site](http://grub.johnlane.ie/grubby-usb.html). But, from what you've written, it sounds like you've already read through all of that.

Just looking at your command-line, it doesn't seem to specify the device of your usb boot device (like my `sdj`) to which you want to write Grub? I imagine you need to point to `grub-install` at the USB device somehow, and also to the EFI partition on your USB device.

It probably doesn't help you right now, but I plan on updating some hardware in the near future and will then need to do an EFI install myself. Oh, and sorry about the delayed response.

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
