### ISSUE TITLE
echo * placeholders?

### ISSUE THREAD

**Issue by sharethewisdom** [johnlane/grub#19]
I recently had a broken laptop keyboard. A few keys that had to be pressed really hard to trigger. My usb keyboards have a different layout and I didn't want to carry them along. So while waiting for 3 weeks for a replacement keyboard I got frustrated typing the long and complicated luks passphrase.

Would you be interested to include another patch? Should [this](https://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/disk/luks.c#n347) be patched so that `*` placeholders are shown?

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
