### ISSUE TITLE
make fails on Debian 11.1  error: alignment 1 of ‘struct grub_btrfs_inode’ is less than 8 [-Werror=packed-not-aligned]

### ISSUE THREAD

**Issue by Veek** [johnlane/grub#23]
```
grub-core/fs/btrfs.c:186:1: error: alignment 1 of ‘struct grub_btrfs_inode’ is less than 8 [-Werror=packed-not-aligned]
  186 | } GRUB_PACKED;
      | ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:6945: grub-core/fs/libgrubmods_a-btrfs.o] Error 1

```
Linux debian 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
after git clone

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
